# Form implementation generated from reading ui file 'moc/mainwindow.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(986, 598)
        self.BTN_LOAD = QtWidgets.QPushButton(parent=MainWindow)
        self.BTN_LOAD.setGeometry(QtCore.QRect(10, 10, 161, 51))
        self.BTN_LOAD.setObjectName("BTN_LOAD")
        self.BTN_ANALYZE = QtWidgets.QPushButton(parent=MainWindow)
        self.BTN_ANALYZE.setGeometry(QtCore.QRect(10, 90, 161, 51))
        self.BTN_ANALYZE.setObjectName("BTN_ANALYZE")
        self.EDIT_LINE = QtWidgets.QLineEdit(parent=MainWindow)
        self.EDIT_LINE.setGeometry(QtCore.QRect(220, 20, 361, 31))
        self.EDIT_LINE.setReadOnly(True)
        self.EDIT_LINE.setObjectName("EDIT_LINE")
        self.EDIT_LOG = QtWidgets.QPlainTextEdit(parent=MainWindow)
        self.EDIT_LOG.setGeometry(QtCore.QRect(240, 100, 571, 451))
        self.EDIT_LOG.setObjectName("EDIT_LOG")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Hockey Puck Tracking"))
        self.BTN_LOAD.setText(_translate("MainWindow", "Load Video"))
        self.BTN_ANALYZE.setText(_translate("MainWindow", "Analyze"))
